/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AppItemsIndexRouteImport } from "./routes/_app/items/index"
import { Route as AppItemsNewRouteImport } from "./routes/_app/items/new"
import { Route as AppItemsItemIdEditRouteImport } from "./routes/_app/items/$itemId/edit"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIndexRoute = AppItemsIndexRouteImport.update({
  id: "/items/",
  path: "/items/",
  getParentRoute: () => AppRoute,
} as any)
const AppItemsNewRoute = AppItemsNewRouteImport.update({
  id: "/items/new",
  path: "/items/new",
  getParentRoute: () => AppRoute,
} as any)
const AppItemsItemIdEditRoute = AppItemsItemIdEditRouteImport.update({
  id: "/items/$itemId/edit",
  path: "/items/$itemId/edit",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/login": typeof LoginRoute
  "/items/new": typeof AppItemsNewRoute
  "/items/": typeof AppItemsIndexRoute
  "/items/$itemId/edit": typeof AppItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/": typeof AppIndexRoute
  "/items/new": typeof AppItemsNewRoute
  "/items": typeof AppItemsIndexRoute
  "/items/$itemId/edit": typeof AppItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/": typeof AppIndexRoute
  "/_app/items/new": typeof AppItemsNewRoute
  "/_app/items/": typeof AppItemsIndexRoute
  "/_app/items/$itemId/edit": typeof AppItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/login" | "/items/new" | "/items/" | "/items/$itemId/edit"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/" | "/items/new" | "/items" | "/items/$itemId/edit"
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/_app/"
    | "/_app/items/new"
    | "/_app/items/"
    | "/_app/items/$itemId/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/items/": {
      id: "/_app/items/"
      path: "/items"
      fullPath: "/items/"
      preLoaderRoute: typeof AppItemsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/items/new": {
      id: "/_app/items/new"
      path: "/items/new"
      fullPath: "/items/new"
      preLoaderRoute: typeof AppItemsNewRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/items/$itemId/edit": {
      id: "/_app/items/$itemId/edit"
      path: "/items/$itemId/edit"
      fullPath: "/items/$itemId/edit"
      preLoaderRoute: typeof AppItemsItemIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppItemsNewRoute: typeof AppItemsNewRoute
  AppItemsIndexRoute: typeof AppItemsIndexRoute
  AppItemsItemIdEditRoute: typeof AppItemsItemIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppItemsNewRoute: AppItemsNewRoute,
  AppItemsIndexRoute: AppItemsIndexRoute,
  AppItemsItemIdEditRoute: AppItemsItemIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
